/*
 * COURSE: EMBEDDED SYSTEMS, HRY411 
 * 
 * test_source.c
 *
 * Milestone1
 * 
 * Authors : Stefanos Kalogerakis, Aris Zervakis
 */ 

#pragma config(Sensor, S1,     LIGHT,          sensorLightActive)
#pragma config(Motor,  motorA,          LMOTOR,        tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorB,          RMOTOR,        tmotorNormal, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
 int velocity = 80;   //Motor's velocity range is between 0 and 100
 int brightness = SensorValue(LIGHT);  //The Sensor Value from the Light Sensor
 

 while(brightness >= 45){            //While the sensor value is equal or higher than 45,move forward
    motor[LMOTOR] = 80;
    motor[RMOTOR] = 80;
 }
}
